version: '3.8'
services:
  nginx:
    image: nginx:1.21.5-alpine
    ports: 
      - "80:80"
    container_name: nginx
    volumes:
      - ./dnw-nginx/nginx.conf:/etc/nginx/nginx.conf
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - backend
      - frontend

  nest:
    build: ./dnw-nest
    ports:
      - "8000:8000"
    container_name: nest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - backend
    depends_on:
      - db  

  next:
    build: 
      context: ./dnw-next
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: next
    restart: "on-failure"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - frontend
    volumes:
      # hot reload를 위해 mount
      - "./dnw-next:/usr/src/dnw-next"
      - "/usr/src/dnw-next/node_modules"
      - "/usr/src/dnw-next/.dnw-next"  

  db:
    image: mariadb:10
    container_name: db
    ports:
      - "3306:3306"
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    env_file: db/.env
    environment:
      TZ: Asia/Seoul
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - backend
  
networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge






